Add docker-compose and fixed dockerfile
Die-Spengergasse/sj2324-5ehif-classproject-ingredients pull request #8
Opened 2023-11-20 15:28 UTC by matthias-puchner

2023-11-20 18:49 UTC, Kemitoxs requested changes
I am interested to know if you tested it before pushing it and how it worked if you did. While the general approach is **ok** I can not see how this could possibly run. You missed out on copying source code and defined an invalid default password for the Neo4J server. 

I was asked by @FlorianKorner  to write down pretty much everything as he also wants to learn. This is why I annotated some comments with "Leave as is" as you can do just that.

Besides the content I am surprised by your approach of the GIT history. Originally you seem to have based it off of `main` and now merging it into `dev`. When you look at the "Files Changed" tab you can see that you supposedly changed a lot of files which could be because of this.

This is most certainly not intended since your branch is originally based off of `main`, so essentially you are connecting the two again. This is possible and should be done eventually so you can leave this part as is.

Unfortunately your solution does not contain a structure to the Docker such that in future other services could be added easily and logically. However adding services is unlikely so you can leave this as is.

2023-11-20 18:49 UTC, Kemitoxs commented on docker-compose.yml
> +    driver: bridge
Usually the convention is it to have volume and network definitions at the bottom. This is an aesthetic thing but makes your code more easily understood by others.

2023-11-20 18:49 UTC, Kemitoxs commented on docker-compose.yml
> +      - "7687:7687"
Leaving the ports exposed in production could be a dangerous move, if this project reaches production I will eat a broom so you can leave this as is. Also this will most definitely help someone debug a wrong query.

2023-11-20 18:49 UTC, Kemitoxs commented on Ingredients/Dockerfile
> +RUN dotnet build "Ingredients.csproj" -c Release -o /app/build
This is the original file from the `main` branch but you commented out two essential lines. Not only do these make it impossible for the program to run but they also prevent you from building the docker image.

What you are missing out on is actually copying the source code into the container, if you do not do this then the application can not start since there is no `static 'Main' method suitable for an entry point [/src/Ingredients.csproj]`.

![image](https://github.com/Die-Spengergasse/sj2324-5ehif-classproject-ingredients/assets/116514739/602b66d3-a73f-4144-99d0-73fb1e328ac5)

Maybe I am missing out on something here but as far as I can tell this can never work and as such you probably didn't test this.

2023-11-20 18:49 UTC, Kemitoxs commented on docker-compose.yml
> +      NEO4J_AUTH: ${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-admin}
This is another case of you can leave the stuff here since I do not think we will ever have a `.env` file to store our credentials. 

What you however can not leave is this default password that violates the minium requirements for Neo4J. It seems you also did not test this or if you did then you already had the `NEO4J_PASSWORD` set in your console which hints to a rather prolonged and painful setup process.

![image](https://github.com/Die-Spengergasse/sj2324-5ehif-classproject-ingredients/assets/116514739/94994ccd-8fb0-4686-8aa6-c9cadce8c900)

Maybe it won't be a bad idea to remove authentication all together to make it easier to work with. Take it straight from the wiki:
![image](https://github.com/Die-Spengergasse/sj2324-5ehif-classproject-ingredients/assets/116514739/4eb6745d-e4ec-4e0c-96b2-2b4f64e4fdf6)

2023-11-20 18:49 UTC, Kemitoxs commented on docker-compose.yml
> +      - ./neo4j.conf:/conf/neo4j.conf
This file does not exist on the host repository. Are you planning to add it later? Is this just generated with ChatGPT and not checked after?

2023-11-20 18:49 UTC, Kemitoxs commented on docker-compose.yml
> +      - "5000:80"
Why mismatch the ports? The `5000` port is used for development purposes and might already be used if another C# application is running. Consider moving this but you can leave this as is.

2023-11-20 18:49 UTC, Kemitoxs commented on docker-compose.yml
> +      - ingredients_data:/app
Why are you sharing the `ingredients` folder with the container if you already copied it previously? And why do you assign a different `ingredients_data` volume to the _**same**_ directory?!

Again I am trying to figure out if I am missing out on something, maybe you can explain it to me tomorrow.

2023-11-20 19:58 UTC, matthias-puchner commented on docker-compose.yml
> +    driver: bridge
will be done chefe

2023-11-20 20:00 UTC, matthias-puchner commented on docker-compose.yml
> +      - "7687:7687"
please eat the broom, sounds healthy

2023-11-20 20:05 UTC, matthias-puchner commented on Ingredients/Dockerfile
> +RUN dotnet build "Ingredients.csproj" -c Release -o /app/build
Since I don't have much experience with a Dockerfile, I attempted to debug it but had difficulty understanding those two lines. After encountering the 'main method does not exist' error, I suspected that the issue lay within the empty program.cs file. Will fix thanks!

2023-11-20 20:08 UTC, matthias-puchner commented on docker-compose.yml
> +      NEO4J_AUTH: ${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-admin}
I'm sorry but you told me to. You told me that we are going to have a .env file and I should have this as variables. Will remove authentication thanks!

2023-11-20 20:10 UTC, matthias-puchner commented on docker-compose.yml
> +      - ./neo4j.conf:/conf/neo4j.conf
I googled best practices for docker-compose files and didn't think it through thoroughly. I apologize for the oversight and will remove it. Thanks!

2023-11-20 20:12 UTC, matthias-puchner commented on docker-compose.yml
> +      - "5000:80"
I will consider moving this. Thanks!

2023-11-20 20:17 UTC, matthias-puchner commented on docker-compose.yml
> +      - ingredients_data:/app
There is indeed a potential redundancy. Will remove line 34. Thanks!

2024-04-08 11:40 UTC, FlorianKorner approved these changes
now works after my commit

2024-04-08 11:40 UTC, merged